try:
    num = 11
    print(num)
    raise ValueError
except:
    print("Exception Occured")